### PR TITLE
Homepage updates

### PR DESCRIPTION
**Pull request by ryan-draper**
Screenshot 2020-07-16 at 11 40 56 PM

Up next: select field / search bar to populate the sortable list

### CODE REVIEW

**Comment by ryan-draper** [comment]
Deployed: https://donations-step-2020-new.appspot.com/

**Comment by ryan-draper** [comment]
@charu0291 What do you mean by the grid? The grid of tags or the grid of charities? Working on refining the submit button now.

**Comment by charu0291** [comment]
> @charu0291 What do you mean by the grid? The grid of tags or the grid of charities? Working on refining the submit button now.

I meant the lines that we show here https://screenshot.googleplex.com/H7aZYUxiccY

**Comment by ryan-draper** [comment]
I centered the tag grid and redesigned the submit button. I decided to also center the instructions at the top (as shown in (1)) because I thought it looked more clean/organized than leaving it left-justified (as shown in (2)).

(1)
Screenshot 2020-07-17 at 6 28 26 PM

(2)
Screenshot 2020-07-17 at 6 28 50 PM

**Pull request merged**
