### PR TITLE
Read more descriptions

### PR DESCRIPTION
**Pull request by tonioshikanlu**
Adds read more to truncate descriptions.

### CODE REVIEW

**Comment by charu0291** [comment]
please add screenshot of latest

**Comment by tonioshikanlu** [comment]
Screen Shot 2020-08-04 at 1 06 24 PM

**Comment by tonioshikanlu** [comment]
Screen Shot 2020-08-04 at 1 06 36 PM

**Comment by charu0291** [comment]
Looks good, should we remove the underline from "Read More"? The blue color already make it highlighted. Adding underline I feel is over doing on that.

**Pull request merged**
