### PR TITLE
Common pagination

### PR DESCRIPTION
**Pull request by tonioshikanlu**
Adds common card UI and pagination to every page

### CODE REVIEW

**Comment by ryan-draper** [comment]
Can we see screenshots of the personalization and trending pages?

**Comment by tonioshikanlu** [comment]
Screen Shot 2020-07-31 at 10 17 15 PM

**Comment by tonioshikanlu** [comment]
Screen Shot 2020-07-31 at 10 17 29 PM

**Comment by tonioshikanlu** [comment]
Screen Shot 2020-07-31 at 10 17 35 PM

**Comment by ryan-draper** [comment]
Can we remove the grey match/trending titles from the top of the cards? That's how it has been on the browse page which looks more clean imo.

**Comment by tonioshikanlu** [comment]
> Are we going to display a portion of the description on the cards?

No I left the description only on the browse page. Should I include it here?

**Comment by charu0291** [comment]
> Can we remove the grey match/trending titles from the top of the cards? That's how it has been on the browse page which looks more clean imo.

Making the cards same across site can be done in a separate PR. lets not block this PR..which takes care of pagination

**Comment by tonioshikanlu** [comment]
> Please add the UI changes that we discussed in meeting. Let us know once done

Do you mind if I make those changes in a separate PR? Those things are a bit separate and I'd prefer to compartmentalize each part.

**Comment by charu0291** [comment]
> > Please add the UI changes that we discussed in meeting. Let us know once done
> 
> Do you mind if I make those changes in a separate PR? Those things are a bit separate and I'd prefer to compartmentalize each part.

Yes, sg.

**Pull request merged**
